# Generated by Django 3.1.7 on 2021-03-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210307_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('public', '公开'), ('private', '私密'), ('draft', '草稿')], max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('public', '公开'), ('private', '私密'), ('draft', '草稿')], max_length=255),
        ),
    ]
